platform :osx, '12'

target 'XYDevTool' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XYDevTool
#  pod 'SnapKit'
#  pod 'Highlightr', '~> 2.1.0'
#pod 'YYUIKit/Foundation', :path => '/Users/quxiaoyou/Desktop/XYUIKit'

end
